"""enhance_media_table_with_metadata

Revision ID: 7223ab158aff
Revises: 7db30c7f2a85
Create Date: 2025-08-27 21:22:38.036378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7223ab158aff'
down_revision: Union[str, Sequence[str], None] = '7db30c7f2a85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('filename', sa.String(length=255), nullable=True))
    op.add_column('media', sa.Column('file_size', sa.BigInteger(), nullable=True))
    op.add_column('media', sa.Column('file_type', sa.String(length=50), nullable=True))
    op.add_column('media', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'created_at')
    op.drop_column('media', 'file_type')
    op.drop_column('media', 'file_size')
    op.drop_column('media', 'filename')
    # ### end Alembic commands ###
