"""add_radius_field_to_issues

Revision ID: 995d85039e5b
Revises: d6d9e8e68c58
Create Date: 2025-08-30 05:38:31.350224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '995d85039e5b'
down_revision: Union[str, Sequence[str], None] = 'd6d9e8e68c58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('radius', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues', 'radius')
    # ### end Alembic commands ###
