"""add_azure_blob_support_to_media

Revision ID: d6d9e8e68c58
Revises: 7223ab158aff
Create Date: 2025-08-30 00:05:17.205420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6d9e8e68c58'
down_revision: Union[str, Sequence[str], None] = '7223ab158aff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('blob_name', sa.String(length=500), nullable=True))
    op.add_column('media', sa.Column('storage_type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'storage_type')
    op.drop_column('media', 'blob_name')
    # ### end Alembic commands ###
